### ISSUE TITLE
TypeError on login

### ISSUE THREAD

**Issue by Baschdl** [KDD-OpenSource/32de-python#60]
```python
[2018-04-04 07:39:10,274] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/32de-python/api/server.py", line 53, in login
    meta_path_loader = MetaPathLoaderDispatcher().get_loader(session['dataset'])
  File "/32de-python/util/meta_path_loader_dispatcher.py", line 50, in get_loader
    return self.dataset_to_loader[dataset]
TypeError: unhashable type: 'dict'
```

**Comment by juliusrueckin** [comment]
Done
